### ISSUE TITLE
multi-node tests

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-stress#4]

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-stress#4` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
