### ISSUE TITLE
no specific zold version

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-stress#5]
Let's make it flexible

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-stress#5` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
