### ISSUE TITLE
heavy load causes errors

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-stress#7]
We are losing transactions with 16 threads and 200+ batch.

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-stress#7` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
